testEndpoint: https://bstackdemo.com

namedTestUrls:
  url_one: https://www.google.com
  url_two: https://www.yahoo.com

driverType: cloudDriver

onPremDriver:
  platforms:
    - name:
      browser: Chrome
      driverPath: /PATH/TO/CHROME/DRIVER
    - name:
      browser: Firefox
      driverPath: /PATH/TO/FIREFOX/DRIVER

cloudDriver:
  hubUrl: https://hub-cloud.browserstack.com/wd/hub
  user: BROWSERSTACK_USERNAME
  accessKey: BROWSERSTACK_ACCESSKEY
  localTunnel:
    enabled: true
    local_options:
      forcelocal: true
      force: true
      verbose: true
  common_capabilities:
    project: BrowserStack Demo Repository
    buildPrefix: browserstack-examples-python
    capabilities:
      browserstack.debug: true
      browserstack.networkLogs: true
      browserstack.console: debug
  platforms:
    - name: Win10_Chrome_Latest-1
      os: Windows
      os_version: '10'
      browser: Chrome
      browser_version: latest-1
      capabilities:
        browserstack.selenium_version: 3.141.59
    - name: OSX_BigSur_Chrome_Latest
      os: OS X
      os_version: Big Sur
      browser: Chrome
      browser_version: latest
      capabilities:
        browserstack.selenium_version: 3.141.59
    - name: Win10_IE11
      os: Windows
      os_version: '10'
      browser: IE
      browser_version: '11.0'
      capabilities:
        browserstack.ie.arch: x32
        browserstack.selenium_version: 3.141.59